### ISSUE TITLE
What format of video file should we input?

### ISSUE THREAD

**Issue by tuf26618** [freder/cinemetrics#1]
Hi Frederic,

I saw your code and find it was really interesting. Right now, we already installed the openCV. However, I have a question: what format of the video file should we input in order to test if the code works well. Do we also need to input meta-data of the video file?

**Comment by suite22** [comment]
I just tested an MP4 on my own fork of this yesterday and it worked great.

Can you elaborate on what you mean by input meta-data? Most of the Python code from @freder includes prompts for what information you need to provide.

**Comment by freder** [comment]
@tuf26618 it should be able to read all video formats that opencv supports. I personally have only used .vob files so far.

the site doesn't load for me atm, but here should be a list of what is supported: [http://opencv.willowgarage.com/wiki/VideoCodecs](http://opencv.willowgarage.com/wiki/VideoCodecs)

**Comment by tuf26618** [comment]
Hi Fred,

Thank you very much for getting me back. I will look into that. By the way,
there are some other people replied to me via github. And he indicated that
he tried with MP4 and it works well.

Ping(Melody), Feng
Media Studies and Production
School of Media and Communication
Temple University
Tel: 215-200-9412
E-mail: tuf26618@temple.edu

**Comment by tuf26618** [comment]
Hi Ben,

I tried with MP4, it works well.  Thank you very much!

**Comment by tuf26618** [comment]
Dear all,

Thank you for sharing and helping. Right now, according to the disclosed
codes, it seems the codes can only generate the visualization of the color
strips and some other dimensions of useful statistics, but not as the
dynamic color wheels showed in Frederic's site. I wonder is there anyway we
can form that kind of visualization? Or as Fredric said, since it is less
documented, so it is not possible for us to achieve that kind of dynamic
color wheel visualization?

In addition, I just have a wild thinking, is there any solution for video
sound visualization, e.g. sound wave visualization? It will be so helpful
for media studies.

**Comment by freder** [comment]
hi,

i had been playing around with audio a little bit, but i chose to concentrate on the visual aspects for the final project, so sound has been a bit neglected, indeed.

at the time i didn't have much programming experience, that's why once in a while i'm thinking that i would like to re-visit the project, clean it up, and maybe even extend it.

my wish list looks s.th. like this:
- clean up / refactor code
- update to python3
- streamline tool chain
- improve algorithms for shot detection, etc.
- add new functionality, like sound analysis
- properly document everything

i saw a few people have actually forked the repo and made their own modifications to the code. — it would be great to have some collaborators on this (looking at @suite22).

@tuf26618, it's correct, i haven't released the original visualization code (which was a [processing](https://processing.org/) sketch). however, I just recently ported the code [to the web](http://cinemetrics.site/). it's not completely done yet, but i think i will open source the code for this.

**Comment by suite22** [comment]
@freder I appreciate the mention. It's exciting to see the new work on http://cinemetrics.site/ - let me know when you decide to open source that, I'd definitely like to contribute.

On my fork, I've been working to wrap the whole project up into a Vagrant environment so other people can get the project running easily. I have a few more issues to address, but it's close to having everything from the original repo at a usable state.

Beyond that, I'd also like to find some ways to streamline tools and expand on the visualization options. For example, the material I started processing was two different seasons of a TV series. What happens when you want to compare 8 episodes with another season's 8 episodes? etc...

If you want any help with the processing project just let me know. Twitter is the easiest way to reach me - https://twitter.com/suite22

Cheers!

**Comment by freder** [comment]
@suite22 
cool, i might come back to you ...
